# Generated by Django 2.0.6 on 2019-04-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantlocation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='owner',
        ),
    ]
